### ISSUE TITLE
Pause timer periodic?

### ISSUE THREAD

**Issue by razein97** [llucax/pausable_timer#19]
Declaring and using the timer in init state does not work like timer.periodic.

**Comment by llucax** [comment]
Hi @razein97, I really don't understand what's not working or what is not working as you expect. Can you provide more information? Ideally a minimal example to reproduce the issue?

Thanks!

**Comment by razein97** [comment]
I think it's my bad. 
I came across this when I was searching for how to pause timer.periodic()
Does this have the same functionality...run a function every x duration.
Thanks.

**Comment by llucax** [comment]
There is no built-in implementation of `PausableTimer.periodic()`, but you can build one with it, there is even an example in the README. If there is enough requests to have it built-in, I might add it.

Shall I close the issue then?

**Comment by razein97** [comment]
Yes. Thank you!

**Comment by razein97** [comment]
-

**Comment by tricaricom** [comment]
The example in the README is not periodic.  I think you should add a periodic() constructor like Timer.periodic().

**Comment by llucax** [comment]
I will create a new issue for this, as it is the second time it comes around. Next time feel free to create an issue yourself (or even better, submit a pull request :)

#45.

**Comment by llucax** [comment]
I'll lock this issue as it was a question. Feel free to ask any questions in the [discussions](https://github.com/llucax/pausable_timer/discussions).
