### ISSUE TITLE
dartfmt may be unnecessary

### ISSUE THREAD

**Issue by zgosalvez** [llucax/pausable_timer#21]
https://github.com/llucax/pausable_timer/blob/40cf0d2d7ae74a9c6ef281c5932106cb44c77e19/.github/workflows/ci.yml#L32

Running the `dartfmt` command in the CI may be unnecessary since https://github.com/llucax/pausable_timer/blob/40cf0d2d7ae74a9c6ef281c5932106cb44c77e19/.github/workflows/ci.yml#L27 already runs it. See https://github.com/zgosalvez/github-actions-analyze-dart/blob/17a5ca792b39421bdaace447ba65be49af8d907d/src/index.js#L96.

**Comment by llucax** [comment]
Thanks for the tip! I can't figure it out easily, will it also check the format for `test/` and `examples/`?

**Comment by zgosalvez** [comment]
Yes, it checks dart files under the working directory.
