### ISSUE TITLE
Use `dart:core` `Stopwatch` instead of depending on `clock`

### ISSUE THREAD

**Issue by vxern** [llucax/pausable_timer#47]
`Stopwatch` exists in `dart:core`, so we should use it in this package instead of depending unnecessarily on `clock`.

**Comment by mateusfccp** [comment]
I don't think it's possible to remove `clock` unless we have a proper way to test `Stopwatch`. By using `dart:core`'s `Stopwatch` we can't reliably emulate time passage, which make the current tests fails.

AFAIK there's no way to test `dart:core`'s `Timer` and `Stopwatch.

**Comment by mateusfccp** [comment]
@llucax Should we close this or should we leave it open until the aforementioned issue is solved?

**Comment by mateusfccp** [comment]
I am going to close this issue.

@vxern Feel free to reopen it if you think it's somehow solvable.
