### ISSUE TITLE
A reference to the `PausableTimer` should be passed into `callback` to eliminate the requirement for storing an instance externally.

### ISSUE THREAD

**Issue by vxern** [llucax/pausable_timer#48]

**Comment by llucax** [comment]
Hi @vxern, thanks for opening the issue. I'm not convinced this is really necessary. Regular dart timers don't get the timer in the callback either and the idea is to use the same interface so they are compatible. Adding this not only will break compatibility with `Timer`, it will also be a breaking change, needing a version 2.0.0.

**Comment by vxern** [comment]
Those are fair points, and it seems like the built-in `Timer`s indeed don't pass an instance of themselves into the callback. I believed they do. Closing.

**Comment by mateusfccp** [comment]
@llucax @vxern

Actually, `Timer.periodic` **does** pass itself as a parameter to the callback.

I don't know exactly why it does not for regular `Timer`, and I also don't really know why it does for `.periodic`.

As we are now implementing periodic (#45), maybe we should reconsider this? I don't know the advantages, though.
